version: '3.3'
services:
  db:
    image: mysql:5.7
    container_name: donghanh
    restart: always
    env_file:
      - .env # Credential file for setting up your database
    ports:
      - '3306:3306' # <Port exposed> : < MySQL Port running inside container>
    expose:
      - '3306' # Opens port 3306 on the container
    volumes:
      - ./mysql-volume:/var/lib/mysql # Where our data will be persisted

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1